name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the containers
        run: docker compose build

      - name: Run Tests
        run: docker compose run --rm web sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Run Lint
        run: docker compose run --rm web sh -c "flake8"
